// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYhFGptwFhUsvHAGUkrmfD2f4_z-vMs-g',
    appId: '1:885129253015:web:4032b2245dd96a39b919d2',
    messagingSenderId: '885129253015',
    projectId: 'instaa-d24f0',
    authDomain: 'instaa-d24f0.firebaseapp.com',
    storageBucket: 'instaa-d24f0.appspot.com',
    measurementId: 'G-EB7JKWVVSF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZUh-qftSRrkVPsSWbxJXvkfDty2DZqaA',
    appId: '1:885129253015:android:b20c0d9540f78539b919d2',
    messagingSenderId: '885129253015',
    projectId: 'instaa-d24f0',
    storageBucket: 'instaa-d24f0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIaXqJWZs86cMxayDkn5ZQF7zUhf90kes',
    appId: '1:885129253015:ios:3a1f4604dfcca06db919d2',
    messagingSenderId: '885129253015',
    projectId: 'instaa-d24f0',
    storageBucket: 'instaa-d24f0.appspot.com',
    iosClientId: '885129253015-9k69gbn2qhlf7vbppaoh9t7novp8hkba.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterInstaa1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIaXqJWZs86cMxayDkn5ZQF7zUhf90kes',
    appId: '1:885129253015:ios:db669b8be91ac462b919d2',
    messagingSenderId: '885129253015',
    projectId: 'instaa-d24f0',
    storageBucket: 'instaa-d24f0.appspot.com',
    iosClientId: '885129253015-6uppr8bicq8cgsogmsncdf1e79fg7556.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterInstaa1.RunnerTests',
  );
}
